-- a(1, 2).nameindex['exprindex'] = 1
-- a += 1; a ..= ''
-- a(); a(true, false)
-- a = `simple`; a = `first {'middle'} end`
-- a //= 5; a ^= 2
-- repeat a+=1 until a >= 5
-- while not a do a //= 1 end
-- if (0) then else end
-- local x, y, z = 1, false
--
-- if true then
--     return "hi"
-- end
--
-- a = (a);
-- a = (0)

-- a, b, c = x()
-- d, e = x(), 0, 1
--
-- a = x()
-- a, b = (x())
local a, b = 1
local a, b = x()
a = 1, 2
a, b = 3

-- a, b,c = 0, x()
